controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
