# controller_manager:
#   ros__parameters:
#     update_rate: 100

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     arm_controller:
#       type: position_controllers/JointGroupPositionController
#       joints:
#         - joint_1
#         - joint_2
#         - joint_3
#         - joint_4
#         - joint_5
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position
#         - velocity

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 2.0
      joint_1:
        trajectory: 0.2
        goal: 0.1
